services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: revcat
    volumes:
      - ./server/create.pgsql:/docker-entrypoint-initdb.d/init.sql